import Enter from "@/components/Enter";
import Video from "@/components/Video";
import Phase from "@/components/Phase";
import Head from "next/head";
import { useState } from "react";
import { data } from "@/data/data";

export default function Home() {
  const [enterPressed, setEnterPressed] = useState(false);
  const [showPresentation, setShowPresentation] = useState(false);
  const [questionPhase, setQuestionPhase] = useState(false);
  const [currentPhase, setCurrentPhase] = useState(0);
  
  const phases = data.phases;
  const numPhases = phases.length;

  const handleEnter = () => {
    setEnterPressed(true);
    // setShowPresentation(true);
    setQuestionPhase(true);
  };

  const handlePresentationEnd = () => {
    setShowPresentation(false);
    setQuestionPhase(true);
  };

  const handlePhaseEnd = () => {
    if (currentPhase < numPhases - 1) {
      setCurrentPhase(currentPhase + 1);
    }else{
      setQuestionPhase(false);
    }
  };

  const handleRestart = () => {
    setCurrentPhase(0);
    setEnterPressed(false);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!enterPressed && <Enter handleEnter={handleEnter} />}
        {/* {showPresentation && (
          <Video
            path={"/videos/presentation.mp4"}
            handleVideoEnd={handlePresentationEnd}
          />
        )} */}
        {questionPhase && (
          <Phase
            key={currentPhase}
            paths={phases[currentPhase].paths}
            numVidsToPlay={phases[currentPhase].numVidsToPlay}
            handlePhaseEnd={handlePhaseEnd}
            useVisualizer={phases[currentPhase].audioVisualizer}
          />
        )}
        {!questionPhase && enterPressed && !showPresentation && (
          <div>
            <button
              className="begin-button"
              onClick={() => handleRestart(false)}
            >
              Start Over
            </button>
          </div>
        )}
      </main>
    </>
  )
}
