import Head from "next/head";
import { useEffect, useState } from "react";
import { data } from "@/data/data";
import PhaseHandler from "@/components/PhaseHandler";
import MicPermission from "@/components/MicPermission";

export default function Home() {
  // State to track if the presentation has started
  const [startPresentation, setStartPresentation] = useState(false);
  // State to track if user has given microphone access
  const [micAccess, setMicAccess] = useState(false);

  // Extract phases array from data
  const phasesData = data.phasesData;

  const handleMicAccess = () => {
    setMicAccess(true);
    setStartPresentation(true);
  };

useEffect(() => {
  const preventDefault = (event) => {
    event.preventDefault();
  };

  document.addEventListener("touchmove", preventDefault, {
    passive: false,
  });

  document.addEventListener("touchend", preventDefault, {
    passive: false,
  });

  document.addEventListener("contextmenu", preventDefault);

  return () => {
    document.removeEventListener("touchmove", preventDefault);
    document.removeEventListener("touchend", preventDefault);
    document.removeEventListener("contextmenu", preventDefault);
  };
}, []);
  

  return (
    <>
      <Head>
        <title>Fortune Teller</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="app">
          {!micAccess && (
            <MicPermission handlePremissionAccepted={handleMicAccess} />
          )}
          {startPresentation && (
            <PhaseHandler
              data={phasesData}
            />
          )}
        </div>
      </main>
    </>
  );
}
