import Head from "next/head";
import { useState } from "react";
import { data } from "@/data/data";
import PhaseHandler from "@/components/PhaseHandler";
import Start from "@/components/Start";
import MicPermission from "@/components/MicPermission";

export default function Home() {
  // State to track if the enter button has been pressed
  const [enterPressed, setEnterPressed] = useState(false);
  // State to track if the presentation has started
  const [startPresentation, setStartPresentation] = useState(false);
  // State to track if user has given microphone access
  const [micAccess, setMicAccess] = useState(false);

  // Extract phases array from data
  const phases = data.phases;

  const handleMicAccess = () => {
    setMicAccess(true);
  }

  // Function tu run after the start button is pressed
  const handleStart = () => {
    setEnterPressed(true);
    setStartPresentation(true);
  };

  // Function to run at the end of the presentation
  const handlePresentationEnd = () => {
    setStartPresentation(false);
  };

  // Function to run when the start over button is pressed
  const handleRestart = () => {
    setStartPresentation(false);
    setEnterPressed(false);
  };

  return (
    <>
      <Head>
        <title>Fortune Teller</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!micAccess && (
          <MicPermission handlePremissionAccepted={handleMicAccess} />
        )}
        {!enterPressed && micAccess && <Start handleStart={handleStart} />}
        {startPresentation && (
          <PhaseHandler
            phases={phases}
            handlePresentationEnd={handlePresentationEnd}
          />
        )}
        {enterPressed && !startPresentation && (
          <div>
            <button className="begin-button" onClick={handleRestart}>
              Start Over
            </button>
          </div>
        )}
      </main>
    </>
  );
}
